FROM oven/bun:1 AS builder

WORKDIR /app

COPY .env .
COPY .env.dev .
COPY .env.local .
COPY .env.dev .
COPY .env.local .

WORKDIR /app/frontend

COPY ./frontend/package.json ./
COPY ./frontend/bun.lock ./

RUN npm install

COPY ./frontend/ ./

EXPOSE 3000

CMD [ "npm", "run", "dev" ]