FROM node:22-alpine AS builder

WORKDIR /app

COPY .env .
COPY .env.dev .
COPY .env.local .

WORKDIR /app/frontend

COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./

RUN npm install

COPY ./frontend/ ./

EXPOSE 3000

CMD [ "npm", "run", "dev" ]