// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
	deleteFoodsById,
	get,
	listFoods,
	listOrdersToday,
	listPollsToday,
	type Options,
	postFoods,
	postPolls,
	postPollsClose,
	postPollsVote,
	putFoodsById,
} from "../sdk.gen";
import type {
	DeleteFoodsByIdData,
	DeleteFoodsByIdError,
	DeleteFoodsByIdResponse,
	GetData,
	ListFoodsData,
	ListOrdersTodayData,
	ListPollsTodayData,
	PostFoodsData,
	PostFoodsError,
	PostFoodsResponse,
	PostPollsCloseData,
	PostPollsCloseError,
	PostPollsCloseResponse,
	PostPollsData,
	PostPollsError,
	PostPollsResponse,
	PostPollsVoteData,
	PostPollsVoteError,
	PostPollsVoteResponse,
	PutFoodsByIdData,
	PutFoodsByIdError,
	PutFoodsByIdResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
	Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
		_id: string;
		_infinite?: boolean;
		tags?: ReadonlyArray<string>;
	},
];

const createQueryKey = <TOptions extends Options>(
	id: string,
	options?: TOptions,
	infinite?: boolean,
	tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
	const params: QueryKey<TOptions>[0] = {
		_id: id,
		baseUrl:
			options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
	} as QueryKey<TOptions>[0];
	if (infinite) {
		params._infinite = infinite;
	}
	if (tags) {
		params.tags = tags;
	}
	if (options?.body) {
		params.body = options.body;
	}
	if (options?.headers) {
		params.headers = options.headers;
	}
	if (options?.path) {
		params.path = options.path;
	}
	if (options?.query) {
		params.query = options.query;
	}
	return [params];
};

export const getQueryKey = (options?: Options<GetData>) =>
	createQueryKey("get", options);

/**
 * Get
 */
export const getOptions = (options?: Options<GetData>) => {
	return queryOptions({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await get({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: getQueryKey(options),
	});
};

export const listFoodsQueryKey = (options?: Options<ListFoodsData>) =>
	createQueryKey("listFoods", options);

/**
 * List foods
 */
export const listFoodsOptions = (options?: Options<ListFoodsData>) => {
	return queryOptions({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listFoods({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: listFoodsQueryKey(options),
	});
};

/**
 * Post foods
 */
export const postFoodsMutation = (
	options?: Partial<Options<PostFoodsData>>,
): UseMutationOptions<
	PostFoodsResponse,
	PostFoodsError,
	Options<PostFoodsData>
> => {
	const mutationOptions: UseMutationOptions<
		PostFoodsResponse,
		PostFoodsError,
		Options<PostFoodsData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postFoods({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

/**
 * Delete foods by ID
 */
export const deleteFoodsByIdMutation = (
	options?: Partial<Options<DeleteFoodsByIdData>>,
): UseMutationOptions<
	DeleteFoodsByIdResponse,
	DeleteFoodsByIdError,
	Options<DeleteFoodsByIdData>
> => {
	const mutationOptions: UseMutationOptions<
		DeleteFoodsByIdResponse,
		DeleteFoodsByIdError,
		Options<DeleteFoodsByIdData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await deleteFoodsById({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

/**
 * Put foods by ID
 */
export const putFoodsByIdMutation = (
	options?: Partial<Options<PutFoodsByIdData>>,
): UseMutationOptions<
	PutFoodsByIdResponse,
	PutFoodsByIdError,
	Options<PutFoodsByIdData>
> => {
	const mutationOptions: UseMutationOptions<
		PutFoodsByIdResponse,
		PutFoodsByIdError,
		Options<PutFoodsByIdData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await putFoodsById({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

export const listOrdersTodayQueryKey = (
	options?: Options<ListOrdersTodayData>,
) => createQueryKey("listOrdersToday", options);

/**
 * List orders today
 */
export const listOrdersTodayOptions = (
	options?: Options<ListOrdersTodayData>,
) => {
	return queryOptions({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listOrdersToday({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: listOrdersTodayQueryKey(options),
	});
};

/**
 * Post polls
 */
export const postPollsMutation = (
	options?: Partial<Options<PostPollsData>>,
): UseMutationOptions<
	PostPollsResponse,
	PostPollsError,
	Options<PostPollsData>
> => {
	const mutationOptions: UseMutationOptions<
		PostPollsResponse,
		PostPollsError,
		Options<PostPollsData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postPolls({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

/**
 * Post polls close
 */
export const postPollsCloseMutation = (
	options?: Partial<Options<PostPollsCloseData>>,
): UseMutationOptions<
	PostPollsCloseResponse,
	PostPollsCloseError,
	Options<PostPollsCloseData>
> => {
	const mutationOptions: UseMutationOptions<
		PostPollsCloseResponse,
		PostPollsCloseError,
		Options<PostPollsCloseData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postPollsClose({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

export const listPollsTodayQueryKey = (options?: Options<ListPollsTodayData>) =>
	createQueryKey("listPollsToday", options);

/**
 * List polls today
 */
export const listPollsTodayOptions = (
	options?: Options<ListPollsTodayData>,
) => {
	return queryOptions({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listPollsToday({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: listPollsTodayQueryKey(options),
	});
};

/**
 * Post polls vote
 */
export const postPollsVoteMutation = (
	options?: Partial<Options<PostPollsVoteData>>,
): UseMutationOptions<
	PostPollsVoteResponse,
	PostPollsVoteError,
	Options<PostPollsVoteData>
> => {
	const mutationOptions: UseMutationOptions<
		PostPollsVoteResponse,
		PostPollsVoteError,
		Options<PostPollsVoteData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postPollsVote({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};
