// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
	deleteFoodsById,
	getAuthCentrifugoToken,
	getAuthImagekitToken,
	getOrderedItems,
	getShoppingOrder,
	listFoods,
	listOrdersToday,
	listPollsToday,
	type Options,
	postFoods,
	postIkWebhook,
	postPolls,
	postPollsByIdClose,
	postPollsByIdVote,
	putFoodsById,
} from "../sdk.gen";
import type {
	DeleteFoodsByIdData,
	DeleteFoodsByIdError,
	DeleteFoodsByIdResponse,
	GetAuthCentrifugoTokenData,
	GetAuthCentrifugoTokenError,
	GetAuthCentrifugoTokenResponse,
	GetAuthImagekitTokenData,
	GetAuthImagekitTokenError,
	GetAuthImagekitTokenResponse,
	GetOrderedItemsData,
	GetOrderedItemsError,
	GetOrderedItemsResponse2,
	GetShoppingOrderData,
	GetShoppingOrderError,
	GetShoppingOrderResponse2,
	ListFoodsData,
	ListFoodsError,
	ListFoodsResponse,
	ListOrdersTodayData,
	ListOrdersTodayError,
	ListOrdersTodayResponse,
	ListPollsTodayData,
	ListPollsTodayError,
	ListPollsTodayResponse,
	PostFoodsData,
	PostFoodsError,
	PostFoodsResponse,
	PostIkWebhookData,
	PostIkWebhookError,
	PostIkWebhookResponse,
	PostPollsByIdCloseData,
	PostPollsByIdCloseError,
	PostPollsByIdCloseResponse,
	PostPollsByIdVoteData,
	PostPollsByIdVoteError,
	PostPollsByIdVoteResponse,
	PostPollsData,
	PostPollsError,
	PostPollsResponse,
	PutFoodsByIdData,
	PutFoodsByIdError,
	PutFoodsByIdResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
	Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
		_id: string;
		_infinite?: boolean;
		tags?: ReadonlyArray<string>;
	},
];

const createQueryKey = <TOptions extends Options>(
	id: string,
	options?: TOptions,
	infinite?: boolean,
	tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
	const params: QueryKey<TOptions>[0] = {
		_id: id,
		baseUrl:
			options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
	} as QueryKey<TOptions>[0];
	if (infinite) {
		params._infinite = infinite;
	}
	if (tags) {
		params.tags = tags;
	}
	if (options?.body) {
		params.body = options.body;
	}
	if (options?.headers) {
		params.headers = options.headers;
	}
	if (options?.path) {
		params.path = options.path;
	}
	if (options?.query) {
		params.query = options.query;
	}
	return [params];
};

export const getAuthCentrifugoTokenQueryKey = (
	options?: Options<GetAuthCentrifugoTokenData>,
) => createQueryKey("getAuthCentrifugoToken", options);

/**
 * Get auth centrifugo token
 */
export const getAuthCentrifugoTokenOptions = (
	options?: Options<GetAuthCentrifugoTokenData>,
) =>
	queryOptions<
		GetAuthCentrifugoTokenResponse,
		GetAuthCentrifugoTokenError,
		GetAuthCentrifugoTokenResponse,
		ReturnType<typeof getAuthCentrifugoTokenQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getAuthCentrifugoToken({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: getAuthCentrifugoTokenQueryKey(options),
	});

export const getAuthImagekitTokenQueryKey = (
	options?: Options<GetAuthImagekitTokenData>,
) => createQueryKey("getAuthImagekitToken", options);

/**
 * Get auth imagekit token
 */
export const getAuthImagekitTokenOptions = (
	options?: Options<GetAuthImagekitTokenData>,
) =>
	queryOptions<
		GetAuthImagekitTokenResponse,
		GetAuthImagekitTokenError,
		GetAuthImagekitTokenResponse,
		ReturnType<typeof getAuthImagekitTokenQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getAuthImagekitToken({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: getAuthImagekitTokenQueryKey(options),
	});

export const listFoodsQueryKey = (options?: Options<ListFoodsData>) =>
	createQueryKey("listFoods", options);

/**
 * List foods
 */
export const listFoodsOptions = (options?: Options<ListFoodsData>) =>
	queryOptions<
		ListFoodsResponse,
		ListFoodsError,
		ListFoodsResponse,
		ReturnType<typeof listFoodsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listFoods({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: listFoodsQueryKey(options),
	});

/**
 * Post foods
 */
export const postFoodsMutation = (
	options?: Partial<Options<PostFoodsData>>,
): UseMutationOptions<
	PostFoodsResponse,
	PostFoodsError,
	Options<PostFoodsData>
> => {
	const mutationOptions: UseMutationOptions<
		PostFoodsResponse,
		PostFoodsError,
		Options<PostFoodsData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postFoods({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

/**
 * Delete foods by ID
 */
export const deleteFoodsByIdMutation = (
	options?: Partial<Options<DeleteFoodsByIdData>>,
): UseMutationOptions<
	DeleteFoodsByIdResponse,
	DeleteFoodsByIdError,
	Options<DeleteFoodsByIdData>
> => {
	const mutationOptions: UseMutationOptions<
		DeleteFoodsByIdResponse,
		DeleteFoodsByIdError,
		Options<DeleteFoodsByIdData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await deleteFoodsById({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

/**
 * Put foods by ID
 */
export const putFoodsByIdMutation = (
	options?: Partial<Options<PutFoodsByIdData>>,
): UseMutationOptions<
	PutFoodsByIdResponse,
	PutFoodsByIdError,
	Options<PutFoodsByIdData>
> => {
	const mutationOptions: UseMutationOptions<
		PutFoodsByIdResponse,
		PutFoodsByIdError,
		Options<PutFoodsByIdData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await putFoodsById({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

/**
 * ImageKit Webhook Handler
 *
 * Handle ImageKit webhooks for video transformations and uploads.
 */
export const postIkWebhookMutation = (
	options?: Partial<Options<PostIkWebhookData>>,
): UseMutationOptions<
	PostIkWebhookResponse,
	PostIkWebhookError,
	Options<PostIkWebhookData>
> => {
	const mutationOptions: UseMutationOptions<
		PostIkWebhookResponse,
		PostIkWebhookError,
		Options<PostIkWebhookData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postIkWebhook({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

export const getOrderedItemsQueryKey = (
	options?: Options<GetOrderedItemsData>,
) => createQueryKey("getOrderedItems", options);

/**
 * Get ordered items
 */
export const getOrderedItemsOptions = (
	options?: Options<GetOrderedItemsData>,
) =>
	queryOptions<
		GetOrderedItemsResponse2,
		GetOrderedItemsError,
		GetOrderedItemsResponse2,
		ReturnType<typeof getOrderedItemsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getOrderedItems({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: getOrderedItemsQueryKey(options),
	});

export const listOrdersTodayQueryKey = (
	options?: Options<ListOrdersTodayData>,
) => createQueryKey("listOrdersToday", options);

/**
 * List orders today
 */
export const listOrdersTodayOptions = (
	options?: Options<ListOrdersTodayData>,
) =>
	queryOptions<
		ListOrdersTodayResponse,
		ListOrdersTodayError,
		ListOrdersTodayResponse,
		ReturnType<typeof listOrdersTodayQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listOrdersToday({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: listOrdersTodayQueryKey(options),
	});

/**
 * Post polls
 */
export const postPollsMutation = (
	options?: Partial<Options<PostPollsData>>,
): UseMutationOptions<
	PostPollsResponse,
	PostPollsError,
	Options<PostPollsData>
> => {
	const mutationOptions: UseMutationOptions<
		PostPollsResponse,
		PostPollsError,
		Options<PostPollsData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postPolls({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

export const listPollsTodayQueryKey = (options?: Options<ListPollsTodayData>) =>
	createQueryKey("listPollsToday", options);

/**
 * List polls today
 */
export const listPollsTodayOptions = (options?: Options<ListPollsTodayData>) =>
	queryOptions<
		ListPollsTodayResponse,
		ListPollsTodayError,
		ListPollsTodayResponse,
		ReturnType<typeof listPollsTodayQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listPollsToday({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: listPollsTodayQueryKey(options),
	});

/**
 * Post polls by ID close
 */
export const postPollsByIdCloseMutation = (
	options?: Partial<Options<PostPollsByIdCloseData>>,
): UseMutationOptions<
	PostPollsByIdCloseResponse,
	PostPollsByIdCloseError,
	Options<PostPollsByIdCloseData>
> => {
	const mutationOptions: UseMutationOptions<
		PostPollsByIdCloseResponse,
		PostPollsByIdCloseError,
		Options<PostPollsByIdCloseData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postPollsByIdClose({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

/**
 * Post polls by ID vote
 */
export const postPollsByIdVoteMutation = (
	options?: Partial<Options<PostPollsByIdVoteData>>,
): UseMutationOptions<
	PostPollsByIdVoteResponse,
	PostPollsByIdVoteError,
	Options<PostPollsByIdVoteData>
> => {
	const mutationOptions: UseMutationOptions<
		PostPollsByIdVoteResponse,
		PostPollsByIdVoteError,
		Options<PostPollsByIdVoteData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await postPollsByIdVote({
				...options,
				...fnOptions,
				throwOnError: true,
			});
			return data;
		},
	};
	return mutationOptions;
};

export const getShoppingOrderQueryKey = (
	options?: Options<GetShoppingOrderData>,
) => createQueryKey("getShoppingOrder", options);

/**
 * Get shopping order
 */
export const getShoppingOrderOptions = (
	options?: Options<GetShoppingOrderData>,
) =>
	queryOptions<
		GetShoppingOrderResponse2,
		GetShoppingOrderError,
		GetShoppingOrderResponse2,
		ReturnType<typeof getShoppingOrderQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getShoppingOrder({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true,
			});
			return data;
		},
		queryKey: getShoppingOrderQueryKey(options),
	});
