// This file is auto-generated by @hey-api/openapi-ts

export const AppMetadataSchema = {
	additionalProperties: false,
	properties: {
		avatar_url: {
			type: "string",
		},
		display_name: {
			type: "string",
		},
		provider: {
			type: "string",
		},
		providers: {
			items: {
				type: "string",
			},
			type: ["array", "null"],
		},
	},
	required: ["avatar_url", "display_name", "provider", "providers"],
	type: "object",
} as const;

export const ErrorDetailSchema = {
	additionalProperties: false,
	properties: {
		location: {
			description:
				"Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'",
			type: "string",
		},
		message: {
			description: "Error message text",
			type: "string",
		},
		value: {
			description: "The value at the given location",
		},
	},
	type: "object",
} as const;

export const ErrorModelSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/ErrorModel.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		detail: {
			description:
				"A human-readable explanation specific to this occurrence of the problem.",
			examples: ["Property foo is required but is missing."],
			type: "string",
		},
		errors: {
			description: "Optional list of individual error details",
			items: {
				$ref: "#/components/schemas/ErrorDetail",
			},
			type: ["array", "null"],
		},
		instance: {
			description:
				"A URI reference that identifies the specific occurrence of the problem.",
			examples: ["https://example.com/error-log/abc123"],
			format: "uri",
			type: "string",
		},
		status: {
			description: "HTTP status code",
			examples: [400],
			format: "int64",
			type: "integer",
		},
		title: {
			description:
				"A short, human-readable summary of the problem type. This value should not change between occurrences of the error.",
			examples: ["Bad Request"],
			type: "string",
		},
		type: {
			default: "about:blank",
			description:
				"A URI reference to human-readable documentation for the error.",
			examples: ["https://example.com/errors/example"],
			format: "uri",
			type: "string",
		},
	},
	type: "object",
} as const;

export const GetFoodsResponseSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/GetFoodsResponse.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		result: {
			items: {
				$ref: "#/components/schemas/GetFoodsResponseItem",
			},
			type: ["array", "null"],
		},
	},
	required: ["result"],
	type: "object",
} as const;

export const GetFoodsResponseItemSchema = {
	additionalProperties: false,
	properties: {
		description: {
			type: "string",
		},
		id: {
			type: "string",
		},
		image_url: {
			type: "string",
		},
		name: {
			type: "string",
		},
		price: {
			format: "double",
			type: "number",
		},
		user_id: {
			type: "string",
		},
	},
	required: ["id", "name", "image_url", "description", "price", "user_id"],
	type: "object",
} as const;

export const IdentitySchema = {
	additionalProperties: false,
	properties: {
		created_at: {
			type: "string",
		},
		email: {
			type: "string",
		},
		id: {
			type: "string",
		},
		identity_data: {
			$ref: "#/components/schemas/IdentityData",
		},
		identity_id: {
			type: "string",
		},
		last_sign_in_at: {
			type: "string",
		},
		provider: {
			type: "string",
		},
		updated_at: {
			type: "string",
		},
		user_id: {
			type: "string",
		},
	},
	required: [
		"identity_id",
		"id",
		"user_id",
		"identity_data",
		"provider",
		"last_sign_in_at",
		"created_at",
		"updated_at",
		"email",
	],
	type: "object",
} as const;

export const IdentityDataSchema = {
	additionalProperties: false,
	properties: {
		email: {
			type: "string",
		},
		email_verified: {
			type: "boolean",
		},
		phone_verified: {
			type: "boolean",
		},
		sub: {
			type: "string",
		},
	},
	required: ["email", "email_verified", "phone_verified", "sub"],
	type: "object",
} as const;

export const UserMetadataSchema = {
	additionalProperties: false,
	properties: {
		email_verified: {
			type: "boolean",
		},
	},
	required: ["email_verified"],
	type: "object",
} as const;

export const ErrorModelWritableSchema = {
	additionalProperties: false,
	properties: {
		detail: {
			description:
				"A human-readable explanation specific to this occurrence of the problem.",
			examples: ["Property foo is required but is missing."],
			type: "string",
		},
		errors: {
			description: "Optional list of individual error details",
			items: {
				$ref: "#/components/schemas/ErrorDetail",
			},
			type: ["array", "null"],
		},
		instance: {
			description:
				"A URI reference that identifies the specific occurrence of the problem.",
			examples: ["https://example.com/error-log/abc123"],
			format: "uri",
			type: "string",
		},
		status: {
			description: "HTTP status code",
			examples: [400],
			format: "int64",
			type: "integer",
		},
		title: {
			description:
				"A short, human-readable summary of the problem type. This value should not change between occurrences of the error.",
			examples: ["Bad Request"],
			type: "string",
		},
		type: {
			default: "about:blank",
			description:
				"A URI reference to human-readable documentation for the error.",
			examples: ["https://example.com/errors/example"],
			format: "uri",
			type: "string",
		},
	},
	type: "object",
} as const;

export const GetFoodsResponseWritableSchema = {
	additionalProperties: false,
	properties: {
		result: {
			items: {
				$ref: "#/components/schemas/GetFoodsResponseItem",
			},
			type: ["array", "null"],
		},
	},
	required: ["result"],
	type: "object",
} as const;
