// This file is auto-generated by @hey-api/openapi-ts

export const AddFoodCommandSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/AddFoodCommand.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		description: {
			description: "A description of the food item",
			type: "string",
		},
		image_file_id: {
			description: "The ID of the image file for the food item",
			type: "string",
		},
		name: {
			description: "The name of the food item",
			type: "string",
		},
		price: {
			description: "The price of the food item in cents",
			format: "int64",
			type: "integer",
		},
	},
	required: ["name", "price", "description"],
	type: "object",
} as const;

export const AddFoodResultSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/AddFoodResult.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		food_id: {
			description: "The ID of the newly created food item",
			type: "string",
		},
	},
	required: ["food_id"],
	type: "object",
} as const;

export const CreatePollCommandSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/CreatePollCommand.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		food_ids: {
			description: "List of food IDs to include in the poll",
			items: {
				type: "string",
			},
			minItems: 1,
			type: "array",
		},
		order_date: {
			description: "Date for which the poll is being created in RFC3339 format",
			format: "date-time",
			type: "string",
		},
		scheduled_close_at: {
			description: "Scheduled closing time for the poll in RFC3339 format",
			format: "date-time",
			type: "string",
		},
		strategy: {
			description: "Polling strategy to be used",
			enum: ["ORDER_PERSONAL_CHOICE", "ORDER_CONSENSUS_ITEM"],
			type: "string",
		},
	},
	required: ["order_date", "scheduled_close_at", "food_ids", "strategy"],
	type: "object",
} as const;

export const CreatePollResponseSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/CreatePollResponse.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		poll_id: {
			description: "The ID of the created poll",
			type: "string",
		},
	},
	required: ["poll_id"],
	type: "object",
} as const;

export const ErrorDetailSchema = {
	additionalProperties: false,
	properties: {
		location: {
			description:
				"Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'",
			type: "string",
		},
		message: {
			description: "Error message text",
			type: "string",
		},
		value: {
			description: "The value at the given location",
		},
	},
	type: "object",
} as const;

export const ErrorModelSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/ErrorModel.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		detail: {
			description:
				"A human-readable explanation specific to this occurrence of the problem.",
			examples: ["Property foo is required but is missing."],
			type: "string",
		},
		errors: {
			description: "Optional list of individual error details",
			items: {
				$ref: "#/components/schemas/ErrorDetail",
			},
			type: "array",
		},
		instance: {
			description:
				"A URI reference that identifies the specific occurrence of the problem.",
			examples: ["https://example.com/error-log/abc123"],
			format: "uri",
			type: "string",
		},
		status: {
			description: "HTTP status code",
			examples: [400],
			format: "int64",
			type: "integer",
		},
		title: {
			description:
				"A short, human-readable summary of the problem type. This value should not change between occurrences of the error.",
			examples: ["Bad Request"],
			type: "string",
		},
		type: {
			default: "about:blank",
			description:
				"A URI reference to human-readable documentation for the error.",
			examples: ["https://example.com/errors/example"],
			format: "uri",
			type: "string",
		},
	},
	type: "object",
} as const;

export const FoodSchema = {
	additionalProperties: false,
	properties: {
		id: {
			type: "string",
		},
		image_url: {
			type: ["string", "null"],
		},
		name: {
			type: "string",
		},
	},
	required: ["id", "name", "image_url"],
	type: "object",
} as const;

export const GetCentrifugoJWTResponseSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/GetCentrifugoJWTResponse.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		token: {
			description: "The generated JWT token for Centrifugo authentication",
			type: "string",
		},
	},
	required: ["token"],
	type: "object",
} as const;

export const GetFoodsQueryResponseSchema = {
	additionalProperties: false,
	properties: {
		description: {
			type: "string",
		},
		id: {
			type: "string",
		},
		image_url: {
			type: ["string", "null"],
		},
		name: {
			type: "string",
		},
		price: {
			format: "int64",
			type: "integer",
		},
		user: {
			$ref: "#/components/schemas/UserProfile",
		},
	},
	required: ["id", "name", "image_url", "description", "price", "user"],
	type: "object",
} as const;

export const GetOrderedItemsResponseSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/GetOrderedItemsResponse.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		items: {
			items: {
				$ref: "#/components/schemas/OrderedItem",
			},
			type: "array",
		},
	},
	required: ["items"],
	type: "object",
} as const;

export const GetShoppingOrderResponseSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/GetShoppingOrderResponse.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		items: {
			items: {
				$ref: "#/components/schemas/ShoppingItem",
			},
			type: "array",
		},
		total_price: {
			format: "int64",
			type: "integer",
		},
	},
	required: ["items", "total_price"],
	type: "object",
} as const;

export const GetTodayOrdersResponseSchema = {
	additionalProperties: false,
	properties: {
		buyer: {
			$ref: "#/components/schemas/UserProfile",
		},
		order_items: {
			items: {
				$ref: "#/components/schemas/OrderItem",
			},
			type: "array",
		},
		poll_id: {
			type: "string",
		},
		total_price: {
			format: "int64",
			type: "integer",
		},
	},
	required: ["poll_id", "buyer", "total_price", "order_items"],
	type: "object",
} as const;

export const GetTodayPollsQueryResponseSchema = {
	additionalProperties: false,
	properties: {
		closed_at: {
			format: "date-time",
			type: ["string", "null"],
		},
		creator: {
			$ref: "#/components/schemas/UserProfile",
		},
		id: {
			type: "string",
		},
		order_date: {
			format: "date-time",
			type: "string",
		},
		poll_options: {
			items: {
				$ref: "#/components/schemas/PollOption",
			},
			type: "array",
		},
		scheduled_closes_at: {
			format: "date-time",
			type: "string",
		},
		strategy: {
			enum: ["ORDER_CONSENSUS_ITEM", "ORDER_PERSONAL_CHOICE"],
			type: "string",
		},
	},
	required: [
		"id",
		"creator",
		"scheduled_closes_at",
		"strategy",
		"closed_at",
		"poll_options",
		"order_date",
	],
	type: "object",
} as const;

export const ImageKitAuthParametersResponseSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: [
				"https://example.com/schemas/ImageKitAuthParametersResponse.json",
			],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		token: {
			description: "The generated JWT token for ImageKit authentication",
			type: "string",
		},
	},
	required: ["token"],
	type: "object",
} as const;

export const OrderItemSchema = {
	additionalProperties: false,
	properties: {
		details: {
			items: {
				$ref: "#/components/schemas/OrderItemDetail",
			},
			type: "array",
		},
		food_image_url: {
			type: ["string", "null"],
		},
		food_name: {
			type: "string",
		},
		price_at_order: {
			format: "int64",
			type: "integer",
		},
	},
	required: ["food_name", "food_image_url", "price_at_order", "details"],
	type: "object",
} as const;

export const OrderItemDetailSchema = {
	additionalProperties: false,
	properties: {
		quantity: {
			format: "int64",
			type: "integer",
		},
		user: {
			$ref: "#/components/schemas/UserProfile",
		},
	},
	required: ["user", "quantity"],
	type: "object",
} as const;

export const OrderedItemSchema = {
	additionalProperties: false,
	properties: {
		buyer: {
			$ref: "#/components/schemas/UserProfile",
		},
		food_id: {
			type: "string",
		},
		food_name: {
			type: "string",
		},
		food_url: {
			type: "string",
		},
		quantity: {
			format: "int64",
			type: "integer",
		},
		total_price: {
			format: "int64",
			type: "integer",
		},
		unit_price: {
			format: "int64",
			type: "integer",
		},
	},
	required: [
		"food_id",
		"food_name",
		"food_url",
		"quantity",
		"unit_price",
		"total_price",
		"buyer",
	],
	type: "object",
} as const;

export const PollOptionSchema = {
	additionalProperties: false,
	properties: {
		food: {
			$ref: "#/components/schemas/Food",
		},
		id: {
			type: "string",
		},
		price_at_creation: {
			format: "int64",
			type: "integer",
		},
		votes: {
			items: {
				$ref: "#/components/schemas/Vote",
			},
			type: "array",
		},
	},
	required: ["id", "food", "price_at_creation", "votes"],
	type: "object",
} as const;

export const Post_by_id_voteRequestSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/Post-by-id-voteRequest.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		poll_option_id: {
			description: "The ID of the poll option to vote for",
			format: "uuid",
			type: "string",
		},
	},
	required: ["poll_option_id"],
	type: "object",
} as const;

export const Put_by_idRequestSchema = {
	additionalProperties: false,
	properties: {
		$schema: {
			description: "A URL to the JSON Schema for this object.",
			examples: ["https://example.com/schemas/Put-by-idRequest.json"],
			format: "uri",
			readOnly: true,
			type: "string",
		},
		description: {
			description: "A description of the food item",
			type: "string",
		},
		image_file_id: {
			description: "The ID of the image file for the food item",
			type: "string",
		},
		name: {
			description: "The name of the food item",
			type: "string",
		},
		price: {
			description: "The price of the food item in cents",
			format: "int64",
			type: "integer",
		},
	},
	required: ["name", "description", "price"],
	type: "object",
} as const;

export const ShoppingItemSchema = {
	additionalProperties: false,
	properties: {
		food_id: {
			type: "string",
		},
		food_name: {
			type: "string",
		},
		quantity: {
			format: "int64",
			type: "integer",
		},
		total_price: {
			format: "int64",
			type: "integer",
		},
		unit_price: {
			format: "int64",
			type: "integer",
		},
		users: {
			items: {
				$ref: "#/components/schemas/UserProfile",
			},
			minItems: 1,
			type: "array",
		},
	},
	required: [
		"food_id",
		"food_name",
		"quantity",
		"unit_price",
		"total_price",
		"users",
	],
	type: "object",
} as const;

export const UserProfileSchema = {
	additionalProperties: false,
	properties: {
		avatar_url: {
			type: "string",
		},
		created_at: {
			format: "date-time",
			type: "string",
		},
		display_name: {
			type: "string",
		},
		id: {
			type: "string",
		},
	},
	required: ["id", "avatar_url", "display_name", "created_at"],
	type: "object",
} as const;

export const VoteSchema = {
	additionalProperties: false,
	properties: {
		voter: {
			$ref: "#/components/schemas/UserProfile",
		},
	},
	required: ["voter"],
	type: "object",
} as const;

export const AddFoodCommandWritableSchema = {
	additionalProperties: false,
	properties: {
		description: {
			description: "A description of the food item",
			type: "string",
		},
		image_file_id: {
			description: "The ID of the image file for the food item",
			type: "string",
		},
		name: {
			description: "The name of the food item",
			type: "string",
		},
		price: {
			description: "The price of the food item in cents",
			format: "int64",
			type: "integer",
		},
	},
	required: ["name", "price", "description"],
	type: "object",
} as const;

export const AddFoodResultWritableSchema = {
	additionalProperties: false,
	properties: {
		food_id: {
			description: "The ID of the newly created food item",
			type: "string",
		},
	},
	required: ["food_id"],
	type: "object",
} as const;

export const CreatePollCommandWritableSchema = {
	additionalProperties: false,
	properties: {
		food_ids: {
			description: "List of food IDs to include in the poll",
			items: {
				type: "string",
			},
			minItems: 1,
			type: "array",
		},
		order_date: {
			description: "Date for which the poll is being created in RFC3339 format",
			format: "date-time",
			type: "string",
		},
		scheduled_close_at: {
			description: "Scheduled closing time for the poll in RFC3339 format",
			format: "date-time",
			type: "string",
		},
		strategy: {
			description: "Polling strategy to be used",
			enum: ["ORDER_PERSONAL_CHOICE", "ORDER_CONSENSUS_ITEM"],
			type: "string",
		},
	},
	required: ["order_date", "scheduled_close_at", "food_ids", "strategy"],
	type: "object",
} as const;

export const CreatePollResponseWritableSchema = {
	additionalProperties: false,
	properties: {
		poll_id: {
			description: "The ID of the created poll",
			type: "string",
		},
	},
	required: ["poll_id"],
	type: "object",
} as const;

export const ErrorModelWritableSchema = {
	additionalProperties: false,
	properties: {
		detail: {
			description:
				"A human-readable explanation specific to this occurrence of the problem.",
			examples: ["Property foo is required but is missing."],
			type: "string",
		},
		errors: {
			description: "Optional list of individual error details",
			items: {
				$ref: "#/components/schemas/ErrorDetail",
			},
			type: "array",
		},
		instance: {
			description:
				"A URI reference that identifies the specific occurrence of the problem.",
			examples: ["https://example.com/error-log/abc123"],
			format: "uri",
			type: "string",
		},
		status: {
			description: "HTTP status code",
			examples: [400],
			format: "int64",
			type: "integer",
		},
		title: {
			description:
				"A short, human-readable summary of the problem type. This value should not change between occurrences of the error.",
			examples: ["Bad Request"],
			type: "string",
		},
		type: {
			default: "about:blank",
			description:
				"A URI reference to human-readable documentation for the error.",
			examples: ["https://example.com/errors/example"],
			format: "uri",
			type: "string",
		},
	},
	type: "object",
} as const;

export const GetCentrifugoJWTResponseWritableSchema = {
	additionalProperties: false,
	properties: {
		token: {
			description: "The generated JWT token for Centrifugo authentication",
			type: "string",
		},
	},
	required: ["token"],
	type: "object",
} as const;

export const GetOrderedItemsResponseWritableSchema = {
	additionalProperties: false,
	properties: {
		items: {
			items: {
				$ref: "#/components/schemas/OrderedItem",
			},
			type: "array",
		},
	},
	required: ["items"],
	type: "object",
} as const;

export const GetShoppingOrderResponseWritableSchema = {
	additionalProperties: false,
	properties: {
		items: {
			items: {
				$ref: "#/components/schemas/ShoppingItem",
			},
			type: "array",
		},
		total_price: {
			format: "int64",
			type: "integer",
		},
	},
	required: ["items", "total_price"],
	type: "object",
} as const;

export const ImageKitAuthParametersResponseWritableSchema = {
	additionalProperties: false,
	properties: {
		token: {
			description: "The generated JWT token for ImageKit authentication",
			type: "string",
		},
	},
	required: ["token"],
	type: "object",
} as const;

export const Post_by_id_voteRequestWritableSchema = {
	additionalProperties: false,
	properties: {
		poll_option_id: {
			description: "The ID of the poll option to vote for",
			format: "uuid",
			type: "string",
		},
	},
	required: ["poll_option_id"],
	type: "object",
} as const;

export const Put_by_idRequestWritableSchema = {
	additionalProperties: false,
	properties: {
		description: {
			description: "A description of the food item",
			type: "string",
		},
		image_file_id: {
			description: "The ID of the image file for the food item",
			type: "string",
		},
		name: {
			description: "The name of the food item",
			type: "string",
		},
		price: {
			description: "The price of the food item in cents",
			format: "int64",
			type: "integer",
		},
	},
	required: ["name", "description", "price"],
	type: "object",
} as const;
