// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	DeleteFoodsByIdData,
	DeleteFoodsByIdErrors,
	DeleteFoodsByIdResponses,
	GetAuthCentrifugoTokenData,
	GetAuthCentrifugoTokenErrors,
	GetAuthCentrifugoTokenResponses,
	GetData,
	GetErrors,
	GetResponses,
	ListFoodsData,
	ListFoodsErrors,
	ListFoodsResponses,
	ListOrdersTodayData,
	ListOrdersTodayErrors,
	ListOrdersTodayResponses,
	ListPollsTodayData,
	ListPollsTodayErrors,
	ListPollsTodayResponses,
	PostFoodsData,
	PostFoodsErrors,
	PostFoodsResponses,
	PostPollsByIdCloseData,
	PostPollsByIdCloseErrors,
	PostPollsByIdCloseResponses,
	PostPollsByIdVoteData,
	PostPollsByIdVoteErrors,
	PostPollsByIdVoteResponses,
	PostPollsData,
	PostPollsErrors,
	PostPollsResponses,
	PutFoodsByIdData,
	PutFoodsByIdErrors,
	PutFoodsByIdResponses,
} from "./types.gen";
import {
	zDeleteFoodsByIdData,
	zDeleteFoodsByIdResponse,
	zGetAuthCentrifugoTokenData,
	zGetAuthCentrifugoTokenResponse,
	zGetData,
	zGetResponse,
	zListFoodsData,
	zListFoodsResponse,
	zListOrdersTodayData,
	zListOrdersTodayResponse,
	zListPollsTodayData,
	zListPollsTodayResponse,
	zPostFoodsData,
	zPostFoodsResponse,
	zPostPollsByIdCloseData,
	zPostPollsByIdCloseResponse,
	zPostPollsByIdVoteData,
	zPostPollsByIdVoteResponse,
	zPostPollsData,
	zPostPollsResponse,
	zPutFoodsByIdData,
	zPutFoodsByIdResponse,
} from "./zod.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const get = <ThrowOnError extends boolean = false>(
	options?: Options<GetData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<GetResponses, GetErrors, ThrowOnError>(
		{
			requestValidator: async (data) => {
				return await zGetData.parseAsync(data);
			},
			responseValidator: async (data) => {
				return await zGetResponse.parseAsync(data);
			},
			url: "/",
			...options,
		},
	);
};

/**
 * Get auth centrifugo token
 */
export const getAuthCentrifugoToken = <ThrowOnError extends boolean = false>(
	options?: Options<GetAuthCentrifugoTokenData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		GetAuthCentrifugoTokenResponses,
		GetAuthCentrifugoTokenErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zGetAuthCentrifugoTokenData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zGetAuthCentrifugoTokenResponse.parseAsync(data);
		},
		url: "/auth/centrifugo/token",
		...options,
	});
};

/**
 * List foods
 */
export const listFoods = <ThrowOnError extends boolean = false>(
	options?: Options<ListFoodsData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		ListFoodsResponses,
		ListFoodsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zListFoodsData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zListFoodsResponse.parseAsync(data);
		},
		url: "/foods/",
		...options,
	});
};

/**
 * Post foods
 */
export const postFoods = <ThrowOnError extends boolean = false>(
	options: Options<PostFoodsData, ThrowOnError>,
) => {
	return (options.client ?? client).post<
		PostFoodsResponses,
		PostFoodsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zPostFoodsData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zPostFoodsResponse.parseAsync(data);
		},
		url: "/foods/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Delete foods by ID
 */
export const deleteFoodsById = <ThrowOnError extends boolean = false>(
	options: Options<DeleteFoodsByIdData, ThrowOnError>,
) => {
	return (options.client ?? client).delete<
		DeleteFoodsByIdResponses,
		DeleteFoodsByIdErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zDeleteFoodsByIdData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zDeleteFoodsByIdResponse.parseAsync(data);
		},
		url: "/foods/{id}",
		...options,
	});
};

/**
 * Put foods by ID
 */
export const putFoodsById = <ThrowOnError extends boolean = false>(
	options: Options<PutFoodsByIdData, ThrowOnError>,
) => {
	return (options.client ?? client).put<
		PutFoodsByIdResponses,
		PutFoodsByIdErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zPutFoodsByIdData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zPutFoodsByIdResponse.parseAsync(data);
		},
		url: "/foods/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * List orders today
 */
export const listOrdersToday = <ThrowOnError extends boolean = false>(
	options?: Options<ListOrdersTodayData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		ListOrdersTodayResponses,
		ListOrdersTodayErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zListOrdersTodayData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zListOrdersTodayResponse.parseAsync(data);
		},
		url: "/orders/today",
		...options,
	});
};

/**
 * Post polls
 */
export const postPolls = <ThrowOnError extends boolean = false>(
	options: Options<PostPollsData, ThrowOnError>,
) => {
	return (options.client ?? client).post<
		PostPollsResponses,
		PostPollsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zPostPollsData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zPostPollsResponse.parseAsync(data);
		},
		url: "/polls/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * List polls today
 */
export const listPollsToday = <ThrowOnError extends boolean = false>(
	options?: Options<ListPollsTodayData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		ListPollsTodayResponses,
		ListPollsTodayErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zListPollsTodayData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zListPollsTodayResponse.parseAsync(data);
		},
		url: "/polls/today",
		...options,
	});
};

/**
 * Post polls by ID close
 */
export const postPollsByIdClose = <ThrowOnError extends boolean = false>(
	options: Options<PostPollsByIdCloseData, ThrowOnError>,
) => {
	return (options.client ?? client).post<
		PostPollsByIdCloseResponses,
		PostPollsByIdCloseErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zPostPollsByIdCloseData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zPostPollsByIdCloseResponse.parseAsync(data);
		},
		url: "/polls/{id}/close",
		...options,
	});
};

/**
 * Post polls by ID vote
 */
export const postPollsByIdVote = <ThrowOnError extends boolean = false>(
	options: Options<PostPollsByIdVoteData, ThrowOnError>,
) => {
	return (options.client ?? client).post<
		PostPollsByIdVoteResponses,
		PostPollsByIdVoteErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => {
			return await zPostPollsByIdVoteData.parseAsync(data);
		},
		responseValidator: async (data) => {
			return await zPostPollsByIdVoteResponse.parseAsync(data);
		},
		url: "/polls/{id}/vote",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};
