// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	DeleteFoodsByIdData,
	DeleteFoodsByIdErrors,
	DeleteFoodsByIdResponses,
	GetData,
	GetErrors,
	GetFoodsData,
	GetFoodsErrors,
	GetFoodsResponses,
	GetResponses,
	PostFoodsData,
	PostFoodsErrors,
	PostFoodsResponses,
	PutFoodsByIdData,
	PutFoodsByIdErrors,
	PutFoodsByIdResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const get = <ThrowOnError extends boolean = false>(
	options?: Options<GetData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<GetResponses, GetErrors, ThrowOnError>(
		{
			url: "/",
			...options,
		},
	);
};

/**
 * Get List Foods
 *
 * Retrieve a list of foods.
 */
export const getFoods = <ThrowOnError extends boolean = false>(
	options?: Options<GetFoodsData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<
		GetFoodsResponses,
		GetFoodsErrors,
		ThrowOnError
	>({
		url: "/foods/",
		...options,
	});
};

/**
 * Add new food
 */
export const postFoods = <ThrowOnError extends boolean = false>(
	options: Options<PostFoodsData, ThrowOnError>,
) => {
	return (options.client ?? client).post<
		PostFoodsResponses,
		PostFoodsErrors,
		ThrowOnError
	>({
		url: "/foods/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Delete a food item by its ID
 */
export const deleteFoodsById = <ThrowOnError extends boolean = false>(
	options: Options<DeleteFoodsByIdData, ThrowOnError>,
) => {
	return (options.client ?? client).delete<
		DeleteFoodsByIdResponses,
		DeleteFoodsByIdErrors,
		ThrowOnError
	>({
		url: "/foods/{id}",
		...options,
	});
};

/**
 * Update food
 */
export const putFoodsById = <ThrowOnError extends boolean = false>(
	options: Options<PutFoodsByIdData, ThrowOnError>,
) => {
	return (options.client ?? client).put<
		PutFoodsByIdResponses,
		PutFoodsByIdErrors,
		ThrowOnError
	>({
		url: "/foods/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};
