// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	DeleteFoodsByIdData,
	DeleteFoodsByIdErrors,
	DeleteFoodsByIdResponses,
	GetAuthCentrifugoTokenData,
	GetAuthCentrifugoTokenErrors,
	GetAuthCentrifugoTokenResponses,
	GetData,
	GetErrors,
	GetOrderedItemsData,
	GetOrderedItemsErrors,
	GetOrderedItemsResponses,
	GetResponses,
	GetShoppingOrderData,
	GetShoppingOrderErrors,
	GetShoppingOrderResponses,
	ListFoodsData,
	ListFoodsErrors,
	ListFoodsResponses,
	ListOrdersTodayData,
	ListOrdersTodayErrors,
	ListOrdersTodayResponses,
	ListPollsTodayData,
	ListPollsTodayErrors,
	ListPollsTodayResponses,
	PostFoodsData,
	PostFoodsErrors,
	PostFoodsResponses,
	PostPollsByIdCloseData,
	PostPollsByIdCloseErrors,
	PostPollsByIdCloseResponses,
	PostPollsByIdVoteData,
	PostPollsByIdVoteErrors,
	PostPollsByIdVoteResponses,
	PostPollsData,
	PostPollsErrors,
	PostPollsResponses,
	PutFoodsByIdData,
	PutFoodsByIdErrors,
	PutFoodsByIdResponses,
} from "./types.gen";
import {
	zDeleteFoodsByIdData,
	zDeleteFoodsByIdResponse,
	zGetAuthCentrifugoTokenData,
	zGetAuthCentrifugoTokenResponse,
	zGetData,
	zGetOrderedItemsData,
	zGetOrderedItemsResponse2,
	zGetResponse,
	zGetShoppingOrderData,
	zGetShoppingOrderResponse2,
	zListFoodsData,
	zListFoodsResponse,
	zListOrdersTodayData,
	zListOrdersTodayResponse,
	zListPollsTodayData,
	zListPollsTodayResponse,
	zPostFoodsData,
	zPostFoodsResponse,
	zPostPollsByIdCloseData,
	zPostPollsByIdCloseResponse,
	zPostPollsByIdVoteData,
	zPostPollsByIdVoteResponse,
	zPostPollsData,
	zPostPollsResponse,
	zPutFoodsByIdData,
	zPutFoodsByIdResponse,
} from "./zod.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const get = <ThrowOnError extends boolean = false>(
	options?: Options<GetData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetResponses, GetErrors, ThrowOnError>({
		requestValidator: async (data) => await zGetData.parseAsync(data),
		responseValidator: async (data) => await zGetResponse.parseAsync(data),
		url: "/",
		...options,
	});

/**
 * Get auth centrifugo token
 */
export const getAuthCentrifugoToken = <ThrowOnError extends boolean = false>(
	options?: Options<GetAuthCentrifugoTokenData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		GetAuthCentrifugoTokenResponses,
		GetAuthCentrifugoTokenErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await zGetAuthCentrifugoTokenData.parseAsync(data),
		responseValidator: async (data) =>
			await zGetAuthCentrifugoTokenResponse.parseAsync(data),
		url: "/auth/centrifugo/token",
		...options,
	});

/**
 * List foods
 */
export const listFoods = <ThrowOnError extends boolean = false>(
	options?: Options<ListFoodsData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		ListFoodsResponses,
		ListFoodsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => await zListFoodsData.parseAsync(data),
		responseValidator: async (data) =>
			await zListFoodsResponse.parseAsync(data),
		url: "/foods/",
		...options,
	});

/**
 * Post foods
 */
export const postFoods = <ThrowOnError extends boolean = false>(
	options: Options<PostFoodsData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		PostFoodsResponses,
		PostFoodsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => await zPostFoodsData.parseAsync(data),
		responseValidator: async (data) =>
			await zPostFoodsResponse.parseAsync(data),
		url: "/foods/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Delete foods by ID
 */
export const deleteFoodsById = <ThrowOnError extends boolean = false>(
	options: Options<DeleteFoodsByIdData, ThrowOnError>,
) =>
	(options.client ?? client).delete<
		DeleteFoodsByIdResponses,
		DeleteFoodsByIdErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await zDeleteFoodsByIdData.parseAsync(data),
		responseValidator: async (data) =>
			await zDeleteFoodsByIdResponse.parseAsync(data),
		url: "/foods/{id}",
		...options,
	});

/**
 * Put foods by ID
 */
export const putFoodsById = <ThrowOnError extends boolean = false>(
	options: Options<PutFoodsByIdData, ThrowOnError>,
) =>
	(options.client ?? client).put<
		PutFoodsByIdResponses,
		PutFoodsByIdErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => await zPutFoodsByIdData.parseAsync(data),
		responseValidator: async (data) =>
			await zPutFoodsByIdResponse.parseAsync(data),
		url: "/foods/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Get ordered items
 */
export const getOrderedItems = <ThrowOnError extends boolean = false>(
	options?: Options<GetOrderedItemsData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		GetOrderedItemsResponses,
		GetOrderedItemsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await zGetOrderedItemsData.parseAsync(data),
		responseValidator: async (data) =>
			await zGetOrderedItemsResponse2.parseAsync(data),
		url: "/ordered-items",
		...options,
	});

/**
 * List orders today
 */
export const listOrdersToday = <ThrowOnError extends boolean = false>(
	options?: Options<ListOrdersTodayData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		ListOrdersTodayResponses,
		ListOrdersTodayErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await zListOrdersTodayData.parseAsync(data),
		responseValidator: async (data) =>
			await zListOrdersTodayResponse.parseAsync(data),
		url: "/orders/today",
		...options,
	});

/**
 * Post polls
 */
export const postPolls = <ThrowOnError extends boolean = false>(
	options: Options<PostPollsData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		PostPollsResponses,
		PostPollsErrors,
		ThrowOnError
	>({
		requestValidator: async (data) => await zPostPollsData.parseAsync(data),
		responseValidator: async (data) =>
			await zPostPollsResponse.parseAsync(data),
		url: "/polls/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * List polls today
 */
export const listPollsToday = <ThrowOnError extends boolean = false>(
	options?: Options<ListPollsTodayData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		ListPollsTodayResponses,
		ListPollsTodayErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await zListPollsTodayData.parseAsync(data),
		responseValidator: async (data) =>
			await zListPollsTodayResponse.parseAsync(data),
		url: "/polls/today",
		...options,
	});

/**
 * Post polls by ID close
 */
export const postPollsByIdClose = <ThrowOnError extends boolean = false>(
	options: Options<PostPollsByIdCloseData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		PostPollsByIdCloseResponses,
		PostPollsByIdCloseErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await zPostPollsByIdCloseData.parseAsync(data),
		responseValidator: async (data) =>
			await zPostPollsByIdCloseResponse.parseAsync(data),
		url: "/polls/{id}/close",
		...options,
	});

/**
 * Post polls by ID vote
 */
export const postPollsByIdVote = <ThrowOnError extends boolean = false>(
	options: Options<PostPollsByIdVoteData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		PostPollsByIdVoteResponses,
		PostPollsByIdVoteErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await zPostPollsByIdVoteData.parseAsync(data),
		responseValidator: async (data) =>
			await zPostPollsByIdVoteResponse.parseAsync(data),
		url: "/polls/{id}/vote",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Get shopping order
 */
export const getShoppingOrder = <ThrowOnError extends boolean = false>(
	options?: Options<GetShoppingOrderData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		GetShoppingOrderResponses,
		GetShoppingOrderErrors,
		ThrowOnError
	>({
		requestValidator: async (data) =>
			await zGetShoppingOrderData.parseAsync(data),
		responseValidator: async (data) =>
			await zGetShoppingOrderResponse2.parseAsync(data),
		url: "/shopping-order",
		...options,
	});
