// This file is auto-generated by @hey-api/openapi-ts

import type { GetFoodsResponse2 } from "./types.gen";

const getFoodsResponseSchemaResponseTransformer = (data: any) => {
	if (data.result) {
		data.result = data.result.map((item: any) => {
			return getFoodsResponseItemSchemaResponseTransformer(item);
		});
	}
	return data;
};

const getFoodsResponseItemSchemaResponseTransformer = (data: any) => {
	data.user = userProfileSchemaResponseTransformer(data.user);
	return data;
};

const userProfileSchemaResponseTransformer = (data: any) => {
	data.created_at = new Date(data.created_at);
	return data;
};

export const getFoodsResponseTransformer = async (
	data: any,
): Promise<GetFoodsResponse2> => {
	data = getFoodsResponseSchemaResponseTransformer(data);
	return data;
};
