// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseURL: `${string}://${string}` | (string & {});
};

export type AppMetadata = {
	avatar_url: string;
	display_name: string;
	provider: string;
	providers: Array<string> | null;
};

export type ErrorDetail = {
	/**
	 * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	 */
	location?: string;
	/**
	 * Error message text
	 */
	message?: string;
	/**
	 * The value at the given location
	 */
	value?: unknown;
};

export type ErrorModel = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 */
	detail?: string;
	/**
	 * Optional list of individual error details
	 */
	errors?: Array<ErrorDetail> | null;
	/**
	 * A URI reference that identifies the specific occurrence of the problem.
	 */
	instance?: string;
	/**
	 * HTTP status code
	 */
	status?: bigint;
	/**
	 * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	 */
	title?: string;
	/**
	 * A URI reference to human-readable documentation for the error.
	 */
	type?: string;
};

export type GetFoodsResponse = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	result: Array<GetFoodsResponseItem> | null;
};

export type GetFoodsResponseItem = {
	description: string;
	id: string;
	image_url: string;
	name: string;
	price: number;
	user_id: string;
};

export type Identity = {
	created_at: string;
	email: string;
	id: string;
	identity_data: IdentityData;
	identity_id: string;
	last_sign_in_at: string;
	provider: string;
	updated_at: string;
	user_id: string;
};

export type IdentityData = {
	email: string;
	email_verified: boolean;
	phone_verified: boolean;
	sub: string;
};

export type UserMetadata = {
	email_verified: boolean;
};

export type ErrorModelWritable = {
	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 */
	detail?: string;
	/**
	 * Optional list of individual error details
	 */
	errors?: Array<ErrorDetail> | null;
	/**
	 * A URI reference that identifies the specific occurrence of the problem.
	 */
	instance?: string;
	/**
	 * HTTP status code
	 */
	status?: bigint;
	/**
	 * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	 */
	title?: string;
	/**
	 * A URI reference to human-readable documentation for the error.
	 */
	type?: string;
};

export type GetFoodsResponseWritable = {
	result: Array<GetFoodsResponseItem> | null;
};

export type GetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/";
};

export type GetErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type GetError = GetErrors[keyof GetErrors];

export type GetResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type GetFoodsData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/foods/";
};

export type GetFoodsErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type GetFoodsError = GetFoodsErrors[keyof GetFoodsErrors];

export type GetFoodsResponses = {
	/**
	 * OK
	 */
	200: GetFoodsResponse;
};

export type GetFoodsResponse2 = GetFoodsResponses[keyof GetFoodsResponses];

export type PostFoodsData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/foods/";
};

export type PostFoodsErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type PostFoodsError = PostFoodsErrors[keyof PostFoodsErrors];

export type PostFoodsResponses = {
	/**
	 * OK
	 */
	200: unknown;
};
