// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: "http://localhost:8080" | (string & {});
};

export type AddFoodCommand = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * A description of the food item
	 */
	description: string;
	/**
	 * The ID of the image file for the food item
	 */
	image_file_id?: string;
	/**
	 * The name of the food item
	 */
	name: string;
	/**
	 * The price of the food item in cents
	 */
	price: number;
};

export type AddFoodResult = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * The ID of the newly created food item
	 */
	food_id: string;
};

export type AppMetadata = {
	avatar_url: string;
	display_name: string;
	provider: string;
	providers: Array<string> | null;
};

export type CreatePollCommand = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * List of food IDs to include in the poll
	 */
	food_ids: Array<string> | null;
	/**
	 * Date for which the poll is being created in RFC3339 format
	 */
	order_date: Date;
	/**
	 * Scheduled closing time for the poll in RFC3339 format
	 */
	scheduled_close_at: Date;
	/**
	 * Polling strategy to be used
	 */
	strategy: "ORDER_MULTIPLE_ITEMS" | "ORDER_CONSENSUS_ITEM";
};

export type CreatePollResponse = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * The ID of the created poll
	 */
	poll_id: string;
};

export type ErrorDetail = {
	/**
	 * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	 */
	location?: string;
	/**
	 * Error message text
	 */
	message?: string;
	/**
	 * The value at the given location
	 */
	value?: unknown;
};

export type ErrorModel = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 */
	detail?: string;
	/**
	 * Optional list of individual error details
	 */
	errors?: Array<ErrorDetail> | null;
	/**
	 * A URI reference that identifies the specific occurrence of the problem.
	 */
	instance?: string;
	/**
	 * HTTP status code
	 */
	status?: number;
	/**
	 * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	 */
	title?: string;
	/**
	 * A URI reference to human-readable documentation for the error.
	 */
	type?: string;
};

export type Food = {
	id: string;
	name: string;
};

export type GetCentrifugoJwtResponse = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * The generated JWT token for Centrifugo authentication
	 */
	token: string;
};

export type GetFoodsQueryResponse = {
	description: string;
	id: string;
	image_url?: string;
	name: string;
	price: number;
	user: UserProfile;
};

export type GetTodayOrdersResponse = {
	buyer: UserProfile;
	order_items: Array<OrderItem> | null;
	poll_id: string;
	total_price: number;
};

export type GetTodayPollsQueryResponse = {
	closed_at: Date | null;
	creator: UserProfile;
	final_total_price: number;
	id: string;
	poll_options: Array<PollOption> | null;
	scheduled_closes_at: Date;
	strategy: string;
};

export type Identity = {
	created_at: string;
	email: string;
	id: string;
	identity_data: IdentityData;
	identity_id: string;
	last_sign_in_at: string;
	provider: string;
	updated_at: string;
	user_id: string;
};

export type IdentityData = {
	email: string;
	email_verified: boolean;
	phone_verified: boolean;
	sub: string;
};

export type OrderItem = {
	details: Array<OrderItemDetail> | null;
	food_image_url: string | null;
	food_name: string;
	price_at_order: number;
};

export type OrderItemDetail = {
	quantity: number;
	user: UserProfile;
};

export type PollOption = {
	food: Food;
	id: string;
	price_at_creation: number;
	votes: Array<Vote> | null;
};

export type PostByIdVoteRequest = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * The ID of the poll option to vote for
	 */
	poll_option_id: string;
};

export type PutByIdRequest = {
	/**
	 * A URL to the JSON Schema for this object.
	 */
	readonly $schema?: string;
	/**
	 * A description of the food item
	 */
	description: string;
	/**
	 * The ID of the image file for the food item
	 */
	image_file_id?: string;
	/**
	 * The name of the food item
	 */
	name: string;
	/**
	 * The price of the food item in cents
	 */
	price: number;
};

export type UserMetadata = {
	email_verified: boolean;
};

export type UserProfile = {
	avatar_url: string;
	created_at: Date;
	display_name: string;
	id: string;
};

export type Vote = {
	voter: UserProfile;
};

export type AddFoodCommandWritable = {
	/**
	 * A description of the food item
	 */
	description: string;
	/**
	 * The ID of the image file for the food item
	 */
	image_file_id?: string;
	/**
	 * The name of the food item
	 */
	name: string;
	/**
	 * The price of the food item in cents
	 */
	price: number;
};

export type AddFoodResultWritable = {
	/**
	 * The ID of the newly created food item
	 */
	food_id: string;
};

export type CreatePollCommandWritable = {
	/**
	 * List of food IDs to include in the poll
	 */
	food_ids: Array<string> | null;
	/**
	 * Date for which the poll is being created in RFC3339 format
	 */
	order_date: Date;
	/**
	 * Scheduled closing time for the poll in RFC3339 format
	 */
	scheduled_close_at: Date;
	/**
	 * Polling strategy to be used
	 */
	strategy: "ORDER_MULTIPLE_ITEMS" | "ORDER_CONSENSUS_ITEM";
};

export type CreatePollResponseWritable = {
	/**
	 * The ID of the created poll
	 */
	poll_id: string;
};

export type ErrorModelWritable = {
	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 */
	detail?: string;
	/**
	 * Optional list of individual error details
	 */
	errors?: Array<ErrorDetail> | null;
	/**
	 * A URI reference that identifies the specific occurrence of the problem.
	 */
	instance?: string;
	/**
	 * HTTP status code
	 */
	status?: number;
	/**
	 * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	 */
	title?: string;
	/**
	 * A URI reference to human-readable documentation for the error.
	 */
	type?: string;
};

export type GetCentrifugoJwtResponseWritable = {
	/**
	 * The generated JWT token for Centrifugo authentication
	 */
	token: string;
};

export type PostByIdVoteRequestWritable = {
	/**
	 * The ID of the poll option to vote for
	 */
	poll_option_id: string;
};

export type PutByIdRequestWritable = {
	/**
	 * A description of the food item
	 */
	description: string;
	/**
	 * The ID of the image file for the food item
	 */
	image_file_id?: string;
	/**
	 * The name of the food item
	 */
	name: string;
	/**
	 * The price of the food item in cents
	 */
	price: number;
};

export type GetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/";
};

export type GetErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type GetError = GetErrors[keyof GetErrors];

export type GetResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type GetAuthCentrifugoTokenData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/centrifugo/token";
};

export type GetAuthCentrifugoTokenErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type GetAuthCentrifugoTokenError =
	GetAuthCentrifugoTokenErrors[keyof GetAuthCentrifugoTokenErrors];

export type GetAuthCentrifugoTokenResponses = {
	/**
	 * OK
	 */
	200: GetCentrifugoJwtResponse;
};

export type GetAuthCentrifugoTokenResponse =
	GetAuthCentrifugoTokenResponses[keyof GetAuthCentrifugoTokenResponses];

export type ListFoodsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * The ID of the user whose foods to retrieve (optional)
		 */
		user_id?: string;
	};
	url: "/foods/";
};

export type ListFoodsErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type ListFoodsError = ListFoodsErrors[keyof ListFoodsErrors];

export type ListFoodsResponses = {
	/**
	 * OK
	 */
	200: Array<GetFoodsQueryResponse> | null;
};

export type ListFoodsResponse = ListFoodsResponses[keyof ListFoodsResponses];

export type PostFoodsData = {
	body: AddFoodCommandWritable;
	path?: never;
	query?: never;
	url: "/foods/";
};

export type PostFoodsErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type PostFoodsError = PostFoodsErrors[keyof PostFoodsErrors];

export type PostFoodsResponses = {
	/**
	 * OK
	 */
	200: AddFoodResult;
};

export type PostFoodsResponse = PostFoodsResponses[keyof PostFoodsResponses];

export type DeleteFoodsByIdData = {
	body?: never;
	path: {
		/**
		 * The ID of the food item to be deleted
		 */
		id: string;
	};
	query?: never;
	url: "/foods/{id}";
};

export type DeleteFoodsByIdErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type DeleteFoodsByIdError =
	DeleteFoodsByIdErrors[keyof DeleteFoodsByIdErrors];

export type DeleteFoodsByIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type DeleteFoodsByIdResponse =
	DeleteFoodsByIdResponses[keyof DeleteFoodsByIdResponses];

export type PutFoodsByIdData = {
	body: PutByIdRequestWritable;
	path: {
		/**
		 * The ID of the food item to be updated
		 */
		id: string;
	};
	query?: never;
	url: "/foods/{id}";
};

export type PutFoodsByIdErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type PutFoodsByIdError = PutFoodsByIdErrors[keyof PutFoodsByIdErrors];

export type PutFoodsByIdResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type PutFoodsByIdResponse =
	PutFoodsByIdResponses[keyof PutFoodsByIdResponses];

export type ListOrdersTodayData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/orders/today";
};

export type ListOrdersTodayErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type ListOrdersTodayError =
	ListOrdersTodayErrors[keyof ListOrdersTodayErrors];

export type ListOrdersTodayResponses = {
	/**
	 * OK
	 */
	200: Array<GetTodayOrdersResponse> | null;
};

export type ListOrdersTodayResponse =
	ListOrdersTodayResponses[keyof ListOrdersTodayResponses];

export type PostPollsData = {
	body: CreatePollCommandWritable;
	path?: never;
	query?: never;
	url: "/polls/";
};

export type PostPollsErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type PostPollsError = PostPollsErrors[keyof PostPollsErrors];

export type PostPollsResponses = {
	/**
	 * OK
	 */
	200: CreatePollResponse;
};

export type PostPollsResponse = PostPollsResponses[keyof PostPollsResponses];

export type ListPollsTodayData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/polls/today";
};

export type ListPollsTodayErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type ListPollsTodayError =
	ListPollsTodayErrors[keyof ListPollsTodayErrors];

export type ListPollsTodayResponses = {
	/**
	 * OK
	 */
	200: Array<GetTodayPollsQueryResponse> | null;
};

export type ListPollsTodayResponse =
	ListPollsTodayResponses[keyof ListPollsTodayResponses];

export type PostPollsByIdCloseData = {
	body?: never;
	path: {
		/**
		 * The ID of the poll to be closed
		 */
		id: string;
	};
	query?: never;
	url: "/polls/{id}/close";
};

export type PostPollsByIdCloseErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type PostPollsByIdCloseError =
	PostPollsByIdCloseErrors[keyof PostPollsByIdCloseErrors];

export type PostPollsByIdCloseResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type PostPollsByIdCloseResponse =
	PostPollsByIdCloseResponses[keyof PostPollsByIdCloseResponses];

export type PostPollsByIdVoteData = {
	body: PostByIdVoteRequestWritable;
	path: {
		/**
		 * The ID of the poll to cast a vote on
		 */
		id: string;
	};
	query?: never;
	url: "/polls/{id}/vote";
};

export type PostPollsByIdVoteErrors = {
	/**
	 * Error
	 */
	default: ErrorModel;
};

export type PostPollsByIdVoteError =
	PostPollsByIdVoteErrors[keyof PostPollsByIdVoteErrors];

export type PostPollsByIdVoteResponses = {
	/**
	 * No Content
	 */
	204: void;
};

export type PostPollsByIdVoteResponse =
	PostPollsByIdVoteResponses[keyof PostPollsByIdVoteResponses];
