// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAddFoodCommand = z.object({
    $schema: z.optional(z.url().readonly()),
    description: z.string(),
    image_file_id: z.optional(z.string()),
    name: z.string(),
    price: z.coerce.bigint()
});

export const zAddFoodResult = z.object({
    $schema: z.optional(z.url().readonly()),
    food_id: z.string()
});

export const zCreatePollCommand = z.object({
    $schema: z.optional(z.url().readonly()),
    food_ids: z.array(z.string()).min(1),
    order_date: z.iso.datetime({ offset: true }),
    scheduled_close_at: z.iso.datetime({ offset: true }),
    strategy: z.enum(['ORDER_PERSONAL_CHOICE', 'ORDER_CONSENSUS_ITEM'])
});

export const zCreatePollResponse = z.object({
    $schema: z.optional(z.url().readonly()),
    poll_id: z.string()
});

export const zErrorDetail = z.object({
    location: z.optional(z.string()),
    message: z.optional(z.string()),
    value: z.optional(z.unknown())
});

export const zErrorModel = z.object({
    $schema: z.optional(z.url().readonly()),
    detail: z.optional(z.string()),
    errors: z.optional(z.array(zErrorDetail)),
    instance: z.optional(z.url()),
    status: z.optional(z.coerce.bigint()),
    title: z.optional(z.string()),
    type: z.optional(z.url()).default('about:blank')
});

export const zFood = z.object({
    id: z.string(),
    image_url: z.union([
        z.string(),
        z.null()
    ]),
    name: z.string()
});

export const zGetCentrifugoJwtResponse = z.object({
    $schema: z.optional(z.url().readonly()),
    token: z.string()
});

export const zImageKitAuthParametersResponse = z.object({
    $schema: z.optional(z.url().readonly()),
    token: z.string()
});

export const zPostByIdVoteRequest = z.object({
    $schema: z.optional(z.url().readonly()),
    poll_option_id: z.uuid()
});

export const zPutByIdRequest = z.object({
    $schema: z.optional(z.url().readonly()),
    description: z.string(),
    image_file_id: z.optional(z.string()),
    name: z.string(),
    price: z.coerce.bigint()
});

export const zResponseStructBody = z.object({
    $schema: z.optional(z.url().readonly())
});

export const zSetAvatarRequest = z.object({
    $schema: z.optional(z.url().readonly()),
    avatarUrl: z.string()
});

export const zUserProfile = z.object({
    avatar_url: z.string(),
    created_at: z.iso.datetime({ offset: true }),
    display_name: z.string(),
    id: z.string()
});

export const zGetFoodsQueryResponse = z.object({
    description: z.string(),
    id: z.string(),
    image_url: z.union([
        z.string(),
        z.null()
    ]),
    name: z.string(),
    price: z.coerce.bigint(),
    user: zUserProfile
});

export const zOrderItemDetail = z.object({
    quantity: z.coerce.bigint(),
    user: zUserProfile
});

export const zOrderItem = z.object({
    details: z.array(zOrderItemDetail),
    food_image_url: z.union([
        z.string(),
        z.null()
    ]),
    food_name: z.string(),
    price_at_order: z.coerce.bigint()
});

export const zGetTodayOrdersResponse = z.object({
    buyer: zUserProfile,
    order_items: z.array(zOrderItem),
    poll_id: z.string(),
    total_price: z.coerce.bigint()
});

export const zOrderedItem = z.object({
    buyer: zUserProfile,
    food_id: z.string(),
    food_name: z.string(),
    food_url: z.string(),
    quantity: z.coerce.bigint(),
    total_price: z.coerce.bigint(),
    unit_price: z.coerce.bigint()
});

export const zGetOrderedItemsResponse = z.object({
    $schema: z.optional(z.url().readonly()),
    items: z.array(zOrderedItem)
});

export const zShoppingItem = z.object({
    food_id: z.string(),
    food_name: z.string(),
    quantity: z.coerce.bigint(),
    total_price: z.coerce.bigint(),
    unit_price: z.coerce.bigint(),
    users: z.array(zUserProfile).min(1)
});

export const zGetShoppingOrderResponse = z.object({
    $schema: z.optional(z.url().readonly()),
    items: z.array(zShoppingItem),
    total_price: z.coerce.bigint()
});

export const zVote = z.object({
    voter: zUserProfile
});

export const zPollOption = z.object({
    food: zFood,
    id: z.string(),
    price_at_creation: z.coerce.bigint(),
    votes: z.array(zVote)
});

export const zGetTodayPollsQueryResponse = z.object({
    closed_at: z.union([
        z.iso.datetime({ offset: true }),
        z.null()
    ]),
    creator: zUserProfile,
    id: z.string(),
    order_date: z.iso.datetime({ offset: true }),
    poll_options: z.array(zPollOption),
    scheduled_closes_at: z.iso.datetime({ offset: true }),
    strategy: z.enum(['ORDER_CONSENSUS_ITEM', 'ORDER_PERSONAL_CHOICE'])
});

export const zAddFoodCommandWritable = z.object({
    description: z.string(),
    image_file_id: z.optional(z.string()),
    name: z.string(),
    price: z.coerce.bigint()
});

export const zAddFoodResultWritable = z.object({
    food_id: z.string()
});

export const zCreatePollCommandWritable = z.object({
    food_ids: z.array(z.string()).min(1),
    order_date: z.iso.datetime({ offset: true }),
    scheduled_close_at: z.iso.datetime({ offset: true }),
    strategy: z.enum(['ORDER_PERSONAL_CHOICE', 'ORDER_CONSENSUS_ITEM'])
});

export const zCreatePollResponseWritable = z.object({
    poll_id: z.string()
});

export const zErrorModelWritable = z.object({
    detail: z.optional(z.string()),
    errors: z.optional(z.array(zErrorDetail)),
    instance: z.optional(z.url()),
    status: z.optional(z.coerce.bigint()),
    title: z.optional(z.string()),
    type: z.optional(z.url()).default('about:blank')
});

export const zGetCentrifugoJwtResponseWritable = z.object({
    token: z.string()
});

export const zGetOrderedItemsResponseWritable = z.object({
    items: z.array(zOrderedItem)
});

export const zGetShoppingOrderResponseWritable = z.object({
    items: z.array(zShoppingItem),
    total_price: z.coerce.bigint()
});

export const zImageKitAuthParametersResponseWritable = z.object({
    token: z.string()
});

export const zPostByIdVoteRequestWritable = z.object({
    poll_option_id: z.uuid()
});

export const zPutByIdRequestWritable = z.object({
    description: z.string(),
    image_file_id: z.optional(z.string()),
    name: z.string(),
    price: z.coerce.bigint()
});

export const zSetAvatarRequestWritable = z.object({
    avatarUrl: z.string()
});

export const zGetAuthCentrifugoTokenData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAuthCentrifugoTokenResponse = zGetCentrifugoJwtResponse;

export const zPostAuthImagekitAvatarData = z.object({
    body: zSetAvatarRequestWritable,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthImagekitAvatarResponse = zResponseStructBody;

export const zGetAuthImagekitTokenData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAuthImagekitTokenResponse = zImageKitAuthParametersResponse;

export const zListFoodsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        user_id: z.optional(z.uuid())
    }))
});

/**
 * OK
 */
export const zListFoodsResponse = z.array(zGetFoodsQueryResponse);

export const zPostFoodsData = z.object({
    body: zAddFoodCommandWritable,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostFoodsResponse = zAddFoodResult;

export const zDeleteFoodsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zDeleteFoodsByIdResponse = z.void();

export const zPutFoodsByIdData = z.object({
    body: zPutByIdRequestWritable,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zPutFoodsByIdResponse = z.void();

export const zPostIkWebhookData = z.object({
    body: z.string(),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zPostIkWebhookResponse = z.void();

export const zGetOrderedItemsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        date: z.optional(z.iso.datetime({ offset: true }))
    }))
});

/**
 * OK
 */
export const zGetOrderedItemsResponse2 = zGetOrderedItemsResponse;

export const zListOrdersTodayData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zListOrdersTodayResponse = z.array(zGetTodayOrdersResponse);

export const zPostPollsData = z.object({
    body: zCreatePollCommandWritable,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostPollsResponse = zCreatePollResponse;

export const zListPollsTodayData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zListPollsTodayResponse = z.array(zGetTodayPollsQueryResponse);

export const zPostPollsByIdCloseData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zPostPollsByIdCloseResponse = z.void();

export const zPostPollsByIdVoteData = z.object({
    body: zPostByIdVoteRequestWritable,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zPostPollsByIdVoteResponse = z.void();

export const zGetShoppingOrderData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        date: z.optional(z.iso.datetime({ offset: true }))
    }))
});

/**
 * OK
 */
export const zGetShoppingOrderResponse2 = zGetShoppingOrderResponse;
