// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zAppMetadata = z.object({
	avatar_url: z.string(),
	display_name: z.string(),
	provider: z.string(),
	providers: z.union([z.array(z.string()), z.null()]),
});

export const zErrorDetail = z.object({
	location: z.optional(z.string()),
	message: z.optional(z.string()),
	value: z.optional(z.unknown()),
});

export const zErrorModel = z.object({
	$schema: z.optional(z.url().readonly()),
	detail: z.optional(z.string()),
	errors: z.optional(z.union([z.array(zErrorDetail), z.null()])),
	instance: z.optional(z.url()),
	status: z.optional(z.coerce.bigint()),
	title: z.optional(z.string()),
	type: z.optional(z.url()).default("about:blank"),
});

export const zGetFoodsResponseItem = z.object({
	description: z.string(),
	id: z.string(),
	image_url: z.string(),
	name: z.string(),
	price: z.number(),
	user_id: z.string(),
});

export const zGetFoodsResponse = z.object({
	$schema: z.optional(z.url().readonly()),
	result: z.union([z.array(zGetFoodsResponseItem), z.null()]),
});

export const zIdentityData = z.object({
	email: z.string(),
	email_verified: z.boolean(),
	phone_verified: z.boolean(),
	sub: z.string(),
});

export const zIdentity = z.object({
	created_at: z.string(),
	email: z.string(),
	id: z.string(),
	identity_data: zIdentityData,
	identity_id: z.string(),
	last_sign_in_at: z.string(),
	provider: z.string(),
	updated_at: z.string(),
	user_id: z.string(),
});

export const zUserMetadata = z.object({
	email_verified: z.boolean(),
});

export const zErrorModelWritable = z.object({
	detail: z.optional(z.string()),
	errors: z.optional(z.union([z.array(zErrorDetail), z.null()])),
	instance: z.optional(z.url()),
	status: z.optional(z.coerce.bigint()),
	title: z.optional(z.string()),
	type: z.optional(z.url()).default("about:blank"),
});

export const zGetFoodsResponseWritable = z.object({
	result: z.union([z.array(zGetFoodsResponseItem), z.null()]),
});

export const zGetData = z.object({
	body: z.optional(z.never()),
	path: z.optional(z.never()),
	query: z.optional(z.never()),
});

/**
 * No Content
 */
export const zGetResponse = z.void();

export const zGetFoodsData = z.object({
	body: z.optional(z.never()),
	path: z.optional(z.never()),
	query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetFoodsResponse2 = zGetFoodsResponse;

export const zPostFoodsData = z.object({
	body: z.optional(z.never()),
	path: z.optional(z.never()),
	query: z.optional(z.never()),
});
