/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthOauthRouteImport } from './routes/auth/oauth'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as ProtectedProtectedRouteImport } from './routes/_protected/protected'
import { Route as authUpdatePasswordRouteImport } from './routes/(auth)/update-password'
import { Route as authSignUpSuccessRouteImport } from './routes/(auth)/sign-up-success'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedFoodsIndexRouteImport } from './routes/_protected/foods/index'
import { Route as ProtectedSettingsRoutesRouteImport } from './routes/_protected/settings/routes'
import { Route as ProtectedSettingsNotificationsRouteImport } from './routes/_protected/settings/notifications'
import { Route as ProtectedSettingsAccountRouteImport } from './routes/_protected/settings/account'
import { Route as ProtectedPollsTodayIndexRouteImport } from './routes/_protected/polls/today/index'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthOauthRoute = AuthOauthRouteImport.update({
  id: '/auth/oauth',
  path: '/auth/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProtectedRoute = ProtectedProtectedRouteImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const authUpdatePasswordRoute = authUpdatePasswordRouteImport.update({
  id: '/(auth)/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpSuccessRoute = authSignUpSuccessRouteImport.update({
  id: '/(auth)/sign-up-success',
  path: '/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFoodsIndexRoute = ProtectedFoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRoutesRoute = ProtectedSettingsRoutesRouteImport.update({
  id: '/settings/routes',
  path: '/settings/routes',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsNotificationsRoute =
  ProtectedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSettingsAccountRoute =
  ProtectedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPollsTodayIndexRoute =
  ProtectedPollsTodayIndexRouteImport.update({
    id: '/polls/today/',
    path: '/polls/today/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/health': typeof HealthRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/update-password': typeof authUpdatePasswordRoute
  '/protected': typeof ProtectedProtectedRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/': typeof ProtectedIndexRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/settings/routes': typeof ProtectedSettingsRoutesRoute
  '/foods': typeof ProtectedFoodsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/polls/today': typeof ProtectedPollsTodayIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/update-password': typeof authUpdatePasswordRoute
  '/protected': typeof ProtectedProtectedRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/': typeof ProtectedIndexRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/settings/routes': typeof ProtectedSettingsRoutesRoute
  '/foods': typeof ProtectedFoodsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/polls/today': typeof ProtectedPollsTodayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/sign-up-success': typeof authSignUpSuccessRoute
  '/(auth)/update-password': typeof authUpdatePasswordRoute
  '/_protected/protected': typeof ProtectedProtectedRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/oauth': typeof AuthOauthRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
  '/_protected/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/_protected/settings/routes': typeof ProtectedSettingsRoutesRoute
  '/_protected/foods/': typeof ProtectedFoodsIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/polls/today/': typeof ProtectedPollsTodayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/health'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/sign-up-success'
    | '/update-password'
    | '/protected'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/oauth'
    | '/'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/routes'
    | '/foods'
    | '/settings'
    | '/polls/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/sign-up-success'
    | '/update-password'
    | '/protected'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/oauth'
    | '/'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/routes'
    | '/foods'
    | '/settings'
    | '/polls/today'
  id:
    | '__root__'
    | '/_protected'
    | '/health'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/sign-up'
    | '/(auth)/sign-up-success'
    | '/(auth)/update-password'
    | '/_protected/protected'
    | '/auth/confirm'
    | '/auth/error'
    | '/auth/oauth'
    | '/_protected/'
    | '/_protected/settings/account'
    | '/_protected/settings/notifications'
    | '/_protected/settings/routes'
    | '/_protected/foods/'
    | '/_protected/settings/'
    | '/_protected/polls/today/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authSignUpRoute: typeof authSignUpRoute
  authSignUpSuccessRoute: typeof authSignUpSuccessRoute
  authUpdatePasswordRoute: typeof authUpdatePasswordRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthOauthRoute: typeof AuthOauthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/auth/oauth': {
      id: '/auth/oauth'
      path: '/auth/oauth'
      fullPath: '/auth/oauth'
      preLoaderRoute: typeof AuthOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/protected': {
      id: '/_protected/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof ProtectedProtectedRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/(auth)/update-password': {
      id: '/(auth)/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof authUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up-success': {
      id: '/(auth)/sign-up-success'
      path: '/sign-up-success'
      fullPath: '/sign-up-success'
      preLoaderRoute: typeof authSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/foods/': {
      id: '/_protected/foods/'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof ProtectedFoodsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/routes': {
      id: '/_protected/settings/routes'
      path: '/settings/routes'
      fullPath: '/settings/routes'
      preLoaderRoute: typeof ProtectedSettingsRoutesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/notifications': {
      id: '/_protected/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ProtectedSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/polls/today/': {
      id: '/_protected/polls/today/'
      path: '/polls/today'
      fullPath: '/polls/today'
      preLoaderRoute: typeof ProtectedPollsTodayIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedProtectedRoute: typeof ProtectedProtectedRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
  ProtectedSettingsNotificationsRoute: typeof ProtectedSettingsNotificationsRoute
  ProtectedSettingsRoutesRoute: typeof ProtectedSettingsRoutesRoute
  ProtectedFoodsIndexRoute: typeof ProtectedFoodsIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedPollsTodayIndexRoute: typeof ProtectedPollsTodayIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedProtectedRoute: ProtectedProtectedRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
  ProtectedSettingsNotificationsRoute: ProtectedSettingsNotificationsRoute,
  ProtectedSettingsRoutesRoute: ProtectedSettingsRoutesRoute,
  ProtectedFoodsIndexRoute: ProtectedFoodsIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedPollsTodayIndexRoute: ProtectedPollsTodayIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authSignUpRoute: authSignUpRoute,
  authSignUpSuccessRoute: authSignUpSuccessRoute,
  authUpdatePasswordRoute: authUpdatePasswordRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthOauthRoute: AuthOauthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
